# HuskHomesMenus
# © 2025 Sorekill — Apache-2.0
name: HuskHomesMenus
version: 1.1.5
main: net.chumbucket.huskhomesmenus.HuskHomesMenus
api-version: 1.21

depend: [HuskHomes]
softdepend: [PlaceholderAPI, ProtocolLib]

commands:
  hhm:
    description: Reloads the plugin
    usage: /hhm <reload|version>
    permission: huskhomesmenus.admin

  tpa:
    description: Send a teleport request to a player (HuskHomesMenus wrapper)
    usage: /tpa <player>
    permission: huskhomesmenus.tpa
  tpahere:
    description: Ask a player to teleport to you (HuskHomesMenus wrapper)
    usage: /tpahere <player>
    permission: huskhomesmenus.tpahere
  tpaccept:
    description: Accept the latest (or a specific) pending teleport request
    usage: /tpaccept [player]
    permission: huskhomesmenus.tpaccept
  tpdeny:
    description: Deny the latest (or a specific) pending teleport request
    usage: /tpdeny [player]
    permission: huskhomesmenus.tpdeny
  tpatoggle:
    description: Toggle receiving /tpa requests
    usage: /tpatoggle
    permission: huskhomesmenus.tpatoggle
  tpaheretoggle:
    description: Toggle receiving /tpahere requests
    usage: /tpaheretoggle
    permission: huskhomesmenus.tpaheretoggle
  tpauto:
    description: Toggle's tpa's to automatically accept requests
    usage: /tpauto
    permission: huskhomesmenus.tpauto
  tpmenu:
    description: Toggle tp menu's
    usage: /tpmenu
    permission: huskhomesmenus.tpmenu

  home:
    description: Open homes GUI
    usage: /home
    permission: huskhomesmenus.home
  homes:
    description: Open homes GUI
    usage: /homes
    permission: huskhomesmenus.home
  homemenu:
    description: Toggle home menu
    usage: /homemenu
    permission: huskhomesmenus.homemenu

  warp:
    description: Open warps GUI
    usage: /warp
    permission: huskhomesmenus.warp
  warps:
    description: Open warp GUI
    usage: /warps
    permission: huskhomesmenus.warp
  warpmenu:
    description: Toggle warp menu
    usage: /warpmenu
    permission: huskhomesmenus.warpmenu

permissions:
  huskhomesmenus.*:
    description: Grants all HuskHomesMenus permissions
    default: op
    children:
      huskhomesmenus.admin: true
      huskhomesmenus.tpatoggle: true
      huskhomesmenus.tpaheretoggle: true
      huskhomesmenus.tpa: true
      huskhomesmenus.tpahere: true
      huskhomesmenus.tpaccept: true
      huskhomesmenus.tpdeny: true
      huskhomesmenus.tpmenu: true
      huskhomesmenus.tpauto: true
      huskhomesmenus.home: true
      huskhomesmenus.homemenu: true
      huskhomesmenus.warp: true
      huskhomesmenus.warpmenu: true

  huskhomesmenus.admin:
    description: Allows using /hhm version (and other admin info commands)
    default: op

  huskhomesmenus.tpatoggle:
    description: Allows toggling /tpa request reception
    default: false
  huskhomesmenus.tpaheretoggle:
    description: Allows toggling /tpahere request reception
    default: false
  huskhomesmenus.tpauto:
    description: Allows toggling tpa requests to auto accept
    default: false
  huskhomesmenus.tpmenu:
    description: Allows toggling the teleport request GUI menu
    default: false
  huskhomesmenus.tpa:
    description: Allows sending /tpa requests
    default: false
  huskhomesmenus.tpahere:
    description: Allows sending /tpahere requests
    default: false
  huskhomesmenus.tpaccept:
    description: Allows accepting teleport requests
    default: false
  huskhomesmenus.tpdeny:
    description: Allows denying teleport requests
    default: false

  huskhomesmenus.home:
    description: Allows opening home menu
    default: false
  huskhomesmenus.homemenu:
    description: Allows toggling homes menu
    default: false

  huskhomesmenus.warp:
    description: Allows opening warp menu
    default: false
  huskhomesmenus.warpmenu:
    description: Allows toggling warps menu
    default: false